config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :situations
  resources :plants
  devise_for :users, path_prefix: :devise

  root to: redirect('/dashboards'), as: :root

  resources :dashboards, only: :index

  resources :summernote_images, only: :create

  get '/search_address/:cep', to: 'search_address#new', as: :search_address

  namespace :api do
    resources :data, only: :create
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concentration.rb
class Concentration < ApplicationRecord
  belongs_to :user
  belongs_to :element
  belongs_to :measurement, required: false
end

app/models/dri.rb
class Dri < ApplicationRecord
  belongs_to :element
  belongs_to :measurement, required: false

  def self.calculate(concentrations)
    concentrations.map do |concentration|
      values = (concentrations - [concentration]).pluck(:value)
      sum = values.sum { |x| concentration.value / x }
      inverse_sum = values.sum { |x| x / concentration.value }
      Dri.create(value: sum - inverse_sum, element: concentration.element)
    end
  end
end

app/models/element.rb
class Element < ApplicationRecord
  has_many :concentrations, dependent: :destroy
  has_many :dris, dependent: :destroy
end

app/models/measurement.rb
class Measurement < ApplicationRecord
  has_many :concentrations, dependent: :destroy
  has_many :dris, dependent: :destroy

  def self.calculate(irc)
    concentrations = Wavelength.calculate(irc)
    dris = Dri.calculate(concentrations)
    ibn = dris.sum { |dri| dri.value.abs } / 11
    measurement = Measurement.create(ibn: ibn)
    concentrations.each { |c| c.update_attribute(:measurement_id, measurement.id) }
    dris.each { |d| d.update_attribute(:measurement_id, measurement.id) }
    measurement.ibn
  end
end

app/models/plant.rb
class Plant < ApplicationRecord
end

app/models/python.rb
class Python
  def self.run(file)
    `python app/scripts/#{file}`
  end
end

app/models/situation.rb
class Situation < ApplicationRecord
  belongs_to :plant
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wavelength.rb
class Wavelength
  RED_LDR = 850
  RED_LENGTH = 740

  class << self
    def convert(ldr)
      return unless ldr.present?
      (RED_LENGTH * ldr.to_f) / RED_LDR
    end

    def calculate(irc)
      Element.all.map do |element|
        result = element.intersection + element.slope * irc + element.error
        acceptable = result > element.inferior_limit && result < element.upper_limit # TODO: do something if value is not acceptable
        element.concentrations.create(value: result, acceptable: acceptable)
      end
    end
  end
end

app/controllers/api/api_base_controller.rb
class Api::ApiBaseController < ActionController::Base
  # To allow only json request
  protect_from_forgery with: :null_session, if: Proc.new {|c| c.request.format.json? }
end

app/controllers/api/data_controller.rb
class Api::DataController < Api::ApiBaseController
  def create
    irc = Wavelength.convert(params[:_json])
    render json: { ibn: Measurement.calculate(irc) }
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  respond_to :html, :json

  def respond_modal_with(*args, &blk)
    options = args.extract_options!
    options[:responder] = ModalResponder
    respond_with(*args, options, &blk)
  end
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

class DashboardsController < ApplicationController
  def index
    @concentrations = Measurement.last.concentrations
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]

  # GET /plants
  def index
    @plants = Plant.all
  end

  # GET /plants/1
  def show
  end

  # GET /plants/new
  def new
    @plant = Plant.new
  end

  # GET /plants/1/edit
  def edit
  end

  # POST /plants
  def create
    @plant = Plant.new(plant_params)

    if @plant.save
      redirect_to @plant, notice: 'Plant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /plants/1
  def update
    if @plant.update(plant_params)
      redirect_to @plant, notice: 'Plant was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /plants/1
  def destroy
    @plant.destroy
    redirect_to plants_url, notice: 'Plant was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def plant_params
      params.require(:plant).permit(:name)
    end
end

app/controllers/situations_controller.rb
class SituationsController < ApplicationController
  before_action :set_situation, only: [:show, :edit, :update, :destroy]

  # GET /situations
  def index
    @situations = Situation.all
  end

  # GET /situations/1
  def show
  end

  # GET /situations/new
  def new
    @situation = Situation.new
  end

  # GET /situations/1/edit
  def edit
  end

  # POST /situations
  def create
    @situation = Situation.new(situation_params)

    if @situation.save
      redirect_to @situation, notice: 'Situation was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /situations/1
  def update
    if @situation.update(situation_params)
      redirect_to @situation, notice: 'Situation was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /situations/1
  def destroy
    @situation.destroy
    redirect_to situations_url, notice: 'Situation was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_situation
      @situation = Situation.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def situation_params
      params.require(:situation).permit(:plant_id, :spectrum, :description)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def collection_boolean
    [['Sim', true], ['Não', false]]
  end

  def menu_active(controller)
    if controller.is_a?(Array)
      'active' if controller.any? { |c| c.to_s == controller_path }
    else
      'active' if controller.to_s == controller_path
    end
  end

  def association_for_select(sym_model)
    sym_model.to_s.classify.constantize.all.map { |model| [model.name, model.id] }
  end

  def link_to_menu(title, url, icon, controller = [])
    link_to url, class: menu_active(controller) do
      %(<div class="gui-icon">
          <i class="material-icons">#{icon}</i>
        </div>
        <span class="title">#{title}</span>).html_safe
    end
  end

  def link_to_edit(url)
    link_to fa_icon('pencil'), url, title: 'Editar', class: 'btn btn-floating-action btn-default'
  end

  def link_to_edit_password(url)
    link_to fa_icon('lock'), url, title: 'Editar Senha', class: 'btn btn-floating-action btn-default'
  end

  def link_to_show(url)
    link_to fa_icon('eye'), url, title: 'Visualizar', class: 'btn btn-floating-action btn-info'
  end

  def link_to_destroy(url)
    link_to fa_icon('trash'), url, title: 'Remover', method: :delete,
            data: { confirm: t('texts.actions.confirm') },
            class: 'btn btn-floating-action btn-danger'
  end

  def link_to_modal(label, url, opts = {})
    link_to label, url,
            class: opts[:class] || 'btn btn-default',
            data: { toggle: 'modal', target: '#modal' },
            remote: true
  end

  def link_to_approve(url, opts = {})
    link_to fa_icon('thumbs-up'),
            url,
            method: :post,
            title: 'Aprovar',
            class: opts[:class] || 'btn btn-floating-action btn-success',
            data: { confirm: t('confirm.approval') }
  end

  def link_to_update_password(url)
    link_to fa_icon('lock'), url, method: :patch,
            title: 'Gerar nova Senha',
            class: 'btn btn-floating-action btn-info',
            data: { confirm: 'Deseja realmente gerar uma nova senha?' }
  end

  def link_to_new(resource_url)
    link_to fa_icon('plus'),
            resource_url,
            class: 'btn btn-floating-action btn-primary'
  end
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/situations_helper.rb
module SituationsHelper
end

app/views/dashboards/index.html.erb
<div class="row">
  <div class="text-center">
    <h2>Seja bem vindo ao Produs.</h2>
  </div>
</div>

<hr>

<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-md-12">
        <table class="table">
          <thead>
          <th class="col-md-3">Elemento</th>
          <th class="col-md-3">Concentração</th>
          <th class="col-md-3">Limite Inferior</th>
          <th class="col-md-3">Limite Superior</th>
          </thead>
          <tbody>
          <% @concentrations.each do |concentration| %>
            <tr class="<%= concentration.acceptable ? 'success' : 'danger' %>">
              <td><%= concentration.element.name %></td>
              <td><%= concentration.value.round(4) %></td>
              <td><%= concentration.element.inferior_limit.round(4) %></td>
              <td><%= concentration.element.upper_limit.round(4) %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <!-- BEGIN SITE ACTIVITY -->
  <div class="col-md-9">
    <div class="card ">
      <div class="row">
        <div class="col-md-8">
          <div class="card-head">
            <header>IBN - Índice de balanço nutricional </header>
          </div><!--end .card-head -->
          <div class="card-body height-8">
            <div id="flot-visitors-legend" class="flot-legend-horizontal stick-top-right no-y-padding"></div>
            <div id="flot-visitors" class="flot height-7" data-title="IBN" data-color="#7dd8d2,#0aa89e"></div>
          </div><!--end .card-body -->
        </div><!--end .col -->
        <div class="col-md-4">
          <div class="card-head">
            <header>Status hoje por hectare</header>
          </div>
          <div class="card-body height-8">
            <strong>214</strong> Uvas sadias
            <span class="pull-right text-success text-sm">
              0,18% <%= material_icon.trending_up %></span>
            <div class="progress progress-hairline">
              <div class="progress-bar progress-bar-primary-dark" style="width:43%"></div>
            </div>
            756 Prontas para colheita
            <span class="pull-right text-success text-sm">0,68% <%= material_icon.trending_up %></span>
            <div class="progress progress-hairline">
              <div class="progress-bar progress-bar-primary-dark" style="width:11%"></div>
            </div>
            291 Uvas doentes
            <span class="pull-right text-danger text-sm">21,08% <%= material_icon.trending_down %></span>
            <div class="progress progress-hairline">
              <div class="progress-bar progress-bar-danger" style="width:93%"></div>
            </div>
            32,301 Uvas em entressafra
            <span class="pull-right text-success text-sm">0,18% <%= material_icon.trending_up %></span>
            <div class="progress progress-hairline">
              <div class="progress-bar progress-bar-primary-dark" style="width:63%"></div>
            </div>
            132 Uvas em plantio
            <span class="pull-right text-success text-sm">0,18% <%= material_icon.trending_up %></span>
            <div class="progress progress-hairline">
              <div class="progress-bar progress-bar-primary-dark" style="width:47%"></div>
            </div>
          </div><!--end .card-body -->
        </div><!--end .col -->
      </div><!--end .row -->
    </div><!--end .card -->
  </div><!--end .col -->
  <!-- END SITE ACTIVITY -->

  <!-- BEGIN SERVER STATUS -->
  <div class="col-md-3">
    <div class="card">
      <div class="card-head">
        <header class="text-primary">Temperatura Media</header>
      </div><!--end .card-head -->
      <div class="card-body height-4">
        <div class="pull-right text-center">
          <em class="text-primary">Temperatura</em>
          <br/>
          <div id="serverStatusKnob" class="knob knob-shadow knob-primary knob-body-track size-2">
            <input type="text" class="dial" data-min="0" data-max="100" data-thickness=".09" value="50" data-readOnly=true>
          </div>
        </div>
      </div><!--end .card-body -->
      <div class="card-body height-4 no-padding">
        <div class="stick-bottom-left-right">
          <div id="rickshawGraph" class="height-4" data-color1="#0aa89e" data-color2="rgba(79, 89, 89, 0.2)"></div>
        </div>
      </div><!--end .card-body -->
    </div><!--end .card -->
  </div><!--end .col -->
  <!-- END SERVER STATUS -->
</div><!--end .row -->

<div class="row">

  <!-- BEGIN TODOS -->
  <div class="col-md-3">
    <div class="card ">
      <div class="card-head">
        <header>Tarefas para hoje</header>
        <div class="tools">
          <a class="btn btn-icon-toggle btn-close"><%= material_icon.close.md_18 %></a>
        </div>
      </div><!--end .card-head -->
      <div class="card-body no-padding height-9 scroll">
        <ul class="list" data-sortable="true">
          <li class="tile">
            <div class="checkbox checkbox-styled tile-text">
              <label>
                <input type="checkbox" checked>
                <span>Ligar para fornecedores</span>
              </label>
            </div>
            <a class="btn btn-flat ink-reaction btn-default">
              <%= material_icon.delete %>
            </a>
          </li>
          <li class="tile">
            <div class="checkbox checkbox-styled tile-text">
              <label>
                <input type="checkbox">
                <span>
                  Reunião
                  <small>Funcionários</small>
                </span>
              </label>
            </div>
            <a class="btn btn-flat ink-reaction btn-default">
              <%= material_icon.delete %>
            </a>
          </li>
          <li class="tile">
            <div class="checkbox checkbox-styled tile-text">
              <label>
                <input type="checkbox">
                <span>
                  Verificar histórico semanal
                  <small>Os relatórios da última semana estão prontos para avaliação</small>
                </span>
              </label>
            </div>
            <a class="btn btn-flat ink-reaction btn-default">
              <%= material_icon.delete %>
            </a>
          </li>
          <li class="tile">
            <div class="checkbox checkbox-styled tile-text">
              <label>
                <input type="checkbox">
                <span>Verificar e-mail do SANAR</span>
              </label>
            </div>
            <a class="btn btn-flat ink-reaction btn-default">
              <%= material_icon.delete %>
            </a>
          </li>
          <li class="tile">
            <div class="checkbox checkbox-styled tile-text">
              <label>
                <input type="checkbox">
                <span>Forward important tasks</span>
              </label>
            </div>
            <a class="btn btn-flat ink-reaction btn-default">
              <%= material_icon.delete %>
            </a>
          </li>
          <li class="tile">
            <div class="checkbox checkbox-styled tile-text">
              <label>
                <input type="checkbox">
                <span>Forward important tasks</span>
              </label>
            </div>
            <a class="btn btn-flat ink-reaction btn-default">
              <%= material_icon.delete %>
            </a>
          </li>
        </ul>
      </div><!--end .card-body -->
    </div><!--end .card -->
  </div><!--end .col -->
  <!-- END TODOS -->

  <!-- BEGIN REGISTRATION HISTORY -->
  <div class="col-md-6">
    <div class="card">
      <div class="card-head">
        <header>Historico do hectare 6</header>
        <div class="tools">
          <a class="btn btn-icon-toggle btn-refresh"><%= material_icon.refresh.md_18 %></a>
          <a class="btn btn-icon-toggle btn-collapse"><i class="fa fa-angle-down"></i></a>
          <a class="btn btn-icon-toggle btn-close"><%= material_icon.close.md_18 %></a>
        </div>
      </div><!--end .card-head -->
      <div class="card-body no-padding height-9">
        <div class="row">
          <div class="col-sm-6 hidden-xs">
            <div class="force-padding text-sm text-default-light">
              <p>
                <i class="md md-mode-comment text-primary-light"></i>
                O hectare 6 está em fase de descanso.
              </p>
            </div>
          </div><!--end .col -->
          <div class="col-sm-6">
            <div class="force-padding pull-right text-default-light">
              <h2 class="no-margin text-primary-dark"><span class="text-xxl">66.05%</span></h2>
              <i class="fa fa-caret-up text-success fa-fw"></i> Produtividade da última safra
            </div>
          </div><!--end .col -->
        </div><!--end .row -->
        <div class="stick-bottom-left-right force-padding">
          <div id="flot-registrations" class="flot height-5" data-title="Historico" data-color="#0aa89e"></div>
        </div>
      </div><!--end .card-body -->
    </div><!--end .card -->
  </div><!--end .col -->
  <!-- END REGISTRATION HISTORY -->

  <!-- BEGIN NEW REGISTRATIONS -->
  <div class="col-md-3">
    <div class="card">
      <div class="card-head">
        <header>Funcionários</header>
        <div class="tools hidden-md">
          <a class="btn btn-icon-toggle btn-close">
            <%= material_icon.close.md_18 %>
          </a>
        </div>
      </div><!--end .card-head -->
      <div class="card-body no-padding height-9 scroll">
        <ul class="list divider-full-bleed">
          <li class="tile">
            <div class="tile-content">
              <div class="tile-icon">
                <%= image_tag "avatar9.jpg" %>
              </div>
              <div class="tile-text">Ann Laurens</div>
            </div>
            <a class="btn btn-flat ink-reaction">
              <%= material_icon.block.css_class('text-default-light') %>
            </a>
          </li>
          <li class="tile">
            <div class="tile-content">
              <div class="tile-icon">
                <%= image_tag "avatar4.jpg" %>
              </div>
              <div class="tile-text">Alex Nelson</div>
            </div>
            <a class="btn btn-flat ink-reaction">
              <%= material_icon.block.css_class('text-default-light') %>
            </a>
          </li>
          <li class="tile">
            <div class="tile-content">
              <div class="tile-icon">
                <%= image_tag "avatar11.jpg" %>
              </div>
              <div class="tile-text">Mary Peterson</div>
            </div>
            <a class="btn btn-flat ink-reaction">
              <%= material_icon.block.css_class('text-default-light') %>
            </a>
          </li>
          <li class="tile">
            <div class="tile-content">
              <div class="tile-icon">
                <%= image_tag "avatar7.jpg" %>
              </div>
              <div class="tile-text">Philip Ericsson</div>
            </div>
            <a class="btn btn-flat ink-reaction">
              <%= material_icon.block.css_class('text-default-light') %>
            </a>
          </li>
          <li class="tile">
            <div class="tile-content">
              <div class="tile-icon">
                <%= image_tag "avatar8.jpg" %>
              </div>
              <div class="tile-text">Jim Peters</div>
            </div>
            <a class="btn btn-flat ink-reaction">
              <%= material_icon.block.css_class('text-default-light') %>
            </a>
          </li>
          <li class="tile">
            <div class="tile-content">
              <div class="tile-icon">
                <%= image_tag "avatar2.jpg" %>
              </div>
              <div class="tile-text">Jessica Cruise</div>
            </div>
            <a class="btn btn-flat ink-reaction">
              <%= material_icon.block.css_class('text-default-light') %>
            </a>
          </li>
        </ul>
      </div><!--end .card-body -->
    </div><!--end .card -->
  </div><!--end .col -->
  <!-- END NEW REGISTRATIONS -->
</div><!--end .row -->

app/views/layouts/_menu.html.erb
<!-- BEGIN MENUBAR-->
<div id="menubar" class="menubar-inverse ">
  <div class="menubar-fixed-panel">
    <div>
      <a class="btn btn-icon-toggle btn-default menubar-toggle" data-toggle="menubar" href="javascript:void(0);">
        <i class="fa fa-bars"></i>
      </a>
    </div>
    <div class="expanded">
      <%= link_to dashboards_path do %>
        <span class="text-lg text-bold text-primary ">Produs</span>
      <% end %>
    </div>
  </div>
  <div class="menubar-scroll-panel">

    <!-- BEGIN MAIN MENU -->
    <ul id="main-menu" class="gui-controls">

      <!-- BEGIN DASHBOARD -->
      <li>
        <%= link_to_menu("Dashboard", dashboards_path, "home", :dashboards) %>
      </li>
      <li>
        <%= link_to_menu("Plantas", plants_path, "tonality", :plants) %>
      </li>
      <li>
        <%= link_to_menu("Situações", situations_path, "change_history", :situations) %>
      </li>
      <!-- END DASHBOARD -->

    </ul><!--end .main-menu -->
    <!-- END MAIN MENU -->
  </div><!--end .menubar-scroll-panel-->
</div><!--end #menubar-->
<!-- END MENUBAR -->

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Produs</title>
    <!-- BEGIN META -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <!-- END META -->

    <!-- BEGIN STYLESHEETS -->
    <link href='http://fonts.googleapis.com/css?family=Roboto:300italic,400italic,300,400,500,700,900' rel='stylesheet' type='text/css'/>

    <%= stylesheet_link_tag    'devise', media: 'all' %>
    <!-- END STYLESHEETS -->

    <%= javascript_include_tag 'devise' %>
  </head>

  <body id="body-devise">
    <!-- BEGIN LOGIN SECTION -->
    <section class="section-account">
      <div class="spacer"></div>
      <div class="card contain-xs">
        <div class="card-head">
          <header class="text-center">
            Produs
            <%# image_tag "logo.png", alt: "Produs" %>
          </header>
        </div>
        <div class="card-body">
          <%= render 'shared/toast_messages' %>
          <%= yield %>
        </div><!--end .card-body -->
      </div><!--end .card -->
    </section>
    <!-- END LOGIN SECTION -->
  </body>
</html>

app/views/layouts/modal.html.erb
<!-- remote modal -->
<div class="modal fade" id="remote_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-body">
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/plants/_form.html.erb
<%= simple_form_for(@plant) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/plants/edit.html.erb
<h1>Editing Plant</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Show', @plant %> |
<%= link_to 'Back', plants_path %>

app/views/plants/index.html.erb
<p id="notice"><%= notice %></p>

<% content_for :page_title, 'Plantas' %>

<div class="pull-right">
  <%= link_to_new new_plant_path %>
</div>

<table class="table">
  <thead>
    <tr>
      <th class="col-md-10">Name</th>
      <th class="col-md-2"></th>
    </tr>
  </thead>

  <tbody>
    <% @plants.each do |plant| %>
      <tr>
        <td><%= plant.name %></td>
        <td>
          <%= link_to 'Show', plant %> |
          <%= link_to 'Edit', edit_plant_path(plant) %> |
          <%= link_to 'Destroy', plant, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/plants/new.html.erb
<h1>New Plant</h1>

<%= render 'form', plant: @plant %>

<%= link_to 'Back', plants_path %>

app/views/plants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @plant.name %>
</p>

<%= link_to 'Edit', edit_plant_path(@plant) %> |
<%= link_to 'Back', plants_path %>

app/views/shared/_toast_messages.html.erb
<div id="toast-container" class="toast-top-right">
  <% if flash[:alert] %>
    <div class="toast toast-warning">
      <div class="toast-progress"></div>
      <button type="button" class="toast-close-button">×</button>
      <div class="toast-title">Atenção!</div>
      <div class="toast-message"><%= flash.discard[:alert] %></div>
    </div>
  <% end %>

  <% if flash[:notice] %>
    <div class="toast toast-success">
      <div class="toast-progress"></div>
      <button type="button" class="toast-close-button">×</button>
      <div class="toast-title">Sucesso!</div>
      <div class="toast-message"><%= flash.discard[:notice] %></div>
    </div>
  <% end %>

  <% if flash[:error] %>
    <div class="toast toast-error">
      <div class="toast-progress"></div>
      <button type="button" class="toast-close-button">×</button>
      <div class="toast-title">Erro!</div>
      <div class="toast-message">
        <% if flash[:error].class == String %>
          <%= flash.discard[:error] %>
        <% else %>
          <ul>
            <% flash.discard[:error].each do |error|  %>
              <li><%= error %></li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/situations/_form.html.erb
<%= simple_form_for(@situation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-md-3">
        <%= f.association :plant %>
      </div>
      <div class="col-md-3">
        <%= f.input :description %>
      </div>
      <div class="col-md-3">
        <%= f.input :spectrum %>
      </div>
    </div>
  </div>

  <div class="pull-right form-actions">
    <%= link_to 'Back', situations_path, class: 'btn btn-default' %>
    <%= f.button :submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/situations/edit.html.erb
<h1>Editing Situation</h1>

<%= render 'form', situation: @situation %>

<%= link_to 'Show', @situation %> |
<%= link_to 'Back', situations_path %>

app/views/situations/index.html.erb
<p id="notice"><%= notice %></p>

<% content_for :page_title, 'Situações' %>

<div class="pull-right">
  <%= link_to_new new_situation_path %>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Plant</th>
      <th>Description</th>
      <th>Spectrum</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @situations.each do |situation| %>
      <tr>
        <td><%= situation.plant %></td>
        <td><%= situation.description %></td>
        <td><%= situation.spectrum %></td>
        <td><%= link_to 'Show', situation %></td>
        <td><%= link_to 'Edit', edit_situation_path(situation) %></td>
        <td><%= link_to 'Destroy', situation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/situations/new.html.erb
<h1>New Situation</h1>

<%= render 'form', situation: @situation %>

app/views/situations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plant:</strong>
  <%= @situation.plant %>
</p>

<p>
  <strong>Spectrum:</strong>
  <%= @situation.spectrum %>
</p>

<p>
  <strong>Description:</strong>
  <%= @situation.description %>
</p>

<%= link_to 'Edit', edit_situation_path(@situation) %> |
<%= link_to 'Back', situations_path %>